spring:
  main:
    allow-circular-references: true
  application:
    name: lostAndFind
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(wmwFSvW/mPD+Yw9OrO2nDiOXSeJ870/0hnUrKooItOgPAzi13MrftyAFR+1MjTpE)
#    url: jdbc:mysql://43.142.109.127:3306/findlost
    username: ENC(ljZyVFHv2rZMPDU34JO2+g==)
#    username: findlost
    password: ENC(wmSKEbwGLxLGR+4RHx0e3g==)
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  elasticsearch:
    uris: http://192.168.200.140:9200
    username: demo
    password: 123456
#  kafka:
#    bootstrap-servers: 192.168.200.140:9092
#    producer:
#      bootstrap-servers: 192.168.200.140:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: test
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
#    host: 43.142.109.127
#    password: 123456
    database: 3
#  security:
#    #放行资源（未登录）
#    white-list-urls:
#      - /captcha
#上传文件大小设置
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
jasypt:
  encryptor:
    #加密秘钥
    password: Djk

# 访问白名单路径
secure:
  ignored:
    urls:
      - /
      - /swagger-ui/
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v2/api-docs/**
      - /actuator/**
      - /admin/login
      - /admin/isLogin

#微信小程序
mini:
#  秘钥
    appid: wx3025aaa6ab081c8b
    secret: 1e5bd32e78dd11abbe7d219f1605092b
#    appid: wx2753d757a6568af3
#    secret: e480af9f24471e28ab109f0e8c533d74

